### PR TITLE
Update amazon rds certificate

### PR DESCRIPTION
**Pull request by mrship**
:lock: Update the RDS certificate to the latest 2015 version. 
:memo: This is Amazon's public certificate, not secure information.

### CODE REVIEW

**Comment by matthutchinson** [comment]
:+1:

**Comment by stevecreedon** [comment]
How did I get back onto this ?

**Comment by mezis** [comment]
@stevecreedon dunno, but so did I. Hi, by the way!

**Comment by pedrocunha** [comment]
Because this is a public repo, and you both are watching it? :wave:

**Pull request merged**
